### ISSUE TITLE
Invalid or expired token

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-dirble#13]
The authorisation token that is provided in the sample configuration does not work on my setup.

`api_key = a4c8107f8fe57c235ce48df846720b9c816e8584`

...produces `401` responses from the Dirble server with error message: `Unauthorized. Invalid or expired token.`

The one that is supplied with the Pi MusicBox does work however (`473279e3fa0e7010cbbbb40ecc31890d46e57a2e`).

I'm just looking at Dirble now so have no idea what I am doing, so my apologies in advance if I am being dense.

**Comment by adamcik** [comment]
I think that was just a dummy one, or a key that I deleted. So it wasn't supposed to work. But it's bad form of me to include it in a sample config when it's broken.

I should replace that with a placeholder and a message to register and get your own.
