### ISSUE TITLE
Use Dirble API v2, v1 unavailable June 27

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-dirble#5]
From newsletter email:

> With Dirble v.2 we will also release API v.2 because of the huge refactoring in the database. API v.1 will still exist but will run on the old database so it won't get any new stations. API v.1 will be removed in July the 27th so please migrate to API v.2 before then. You can already look into the API v.2 documentation to see what changes have been made and such:
> https://github.com/Dirble/dirble-api/blob/master/api-doc.md

**Comment by jodal** [comment]
The new API is now available: https://dirble.com/developer/api

Time to switch over.

**Comment by adamcik** [comment]
Almost ready for release now, but feel free to review the changes as I didn't bother to go via a pull request for this.

**Comment by adamcik** [comment]
1.1.0 released :-)
